### ISSUE TITLE
Default command name not used in help output

### ISSUE THREAD

**Issue by jcollado** [sublee/click-default-group#11]
Let's say that I have a command with a default subcommand, when the default subcommand is implicity executed (i.e. subcommand was not typed), whatever value was used as argument is used as the subcommand name in the help string:
```
$ command does-not-exist -h
Usage: command does-not-exist [OPTIONS]
```

even if the subcommand wasn't  passed, it should be part of the help string:
```
$ command does-not-exist -h
Usage: command subcommand [OPTIONS]
```

**Comment by jcollado** [comment]
@sublee I have added a one-line PR that fixes the problem for me. Please have a look at it and let me know.

**Comment by sublee** [comment]
@jcollado I approved your PR. Thank you.
