### ISSUE TITLE
Feature request: pure Python 3 wheel

### ISSUE THREAD

**Issue by simonw** [sublee/click-default-group#21]
I tried to install a package that depends on this inside JupyterLite and got the following error:

> Couldn't find a pure Python 3 wheel for 'click-default-group'

Steps to reproduce: navigate to https://jupyterlite.github.io/demo/lab/index.html and run the following:
```python
import micropip
await micropip.install("sqlite-utils")
```

**Comment by simonw** [comment]
I ported a subset of the test suite to GitHub Actions as part of this - https://github.com/simonw/click-default-group-wheel/blob/master/.github/workflows/test.yml - though I didn't get `coveralls` or Click version 8.0+ working there.

You're welcome to take my `test.yml` file and adapt it for this project if you want to move away from Travis.

**Comment by simonw** [comment]
I've published a package to PyPI under the name `click-default-group-wheel` to unblock my project on this:

- https://pypi.org/project/click-default-group-wheel/
- https://github.com/simonw/click-default-group-wheel/releases/tag/1.2.2

I'll happily retire my package (my replacing it with a version that just depends back on `click-default-group` using the pattern for [pypi-rename](https://github.com/simonw/pypi-rename)) when a version of `click-default-group` ships with a wheel.

I used my new package to ship a new version of `sqlite-utils` with that dependency - which means it now works in both JupyterLite and in the Pyodide REPL!

https://sqlite-utils.datasette.io/en/stable/changelog.html#v3-26-1

Visit https://pyodide.org/en/stable/console.html and try the following:

```pycon
>>> import micropip
>>> await micropip.install("sqlite-utils")
>>> import sqlite_utils
>>> db = sqlite_utils.Database(memory=True)
>>> list(db.query("select 3 * 5"))
[{'3 * 5': 15}]
```

**Comment by webknjaz** [comment]
@simonw the wheel is now published. Though, it's tagged as `py2.py3`.

**Comment by simonw** [comment]
Nice! This is great, thank you.

https://pypi.org/project/click-default-group/1.2.3/#files

<img width="765" alt="CleanShot 2023-09-05 at 19 31 31@2x" src="https://github.com/click-contrib/click-default-group/assets/9599/285fa108-3218-4157-a1f0-cd5c516ec230">

**Comment by simonw** [comment]
I've retired my https://github.com/simonw/click-default-group-wheel repo.

**Comment by simonw** [comment]
I published one last `click-default-group-wheel` package that simply depends on this one - transcript of that here:

https://github.com/simonw/pypi-rename/blob/22e603bf1fc57f54d52c9ef1b361f841e8052f8f/README.md#publishing-your-renamed-package-to-pypi

Package is here: https://pypi.org/project/click-default-group-wheel/
